name: Update Quote Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 2 UTC everyday
    - cron: "0 */24 * * *"

jobs:
  update-readme:
    name: Update Quote README
    runs-on: ubuntu-latest
    steps:
      - uses: siddharth2016/quote-readme@main
        with:
          COMMIT_MESSAGE: Updated Quote in ReadMe.md       # default - Update with quote-readme
          OPTION: quote            # default - both, can be one of (quote, funfact, both), if 'both' then will display either a quote or a fact
          
